### ISSUE TITLE
OmniAuth controller example

### ISSUE THREAD

**Issue by fractaledmind** [rocketshipio/magiclink#1]
I applaud the work being done to show the way for doing OAuth without the OmniAuth gem. I have evolved in this direction over the last couple of years myself. In the OSS spirit, I thought I would just grab some of my controllers and share them with you in case they spark something useful.

Up first is the initial step I took away from OmniAuth. While still using the gem and its strategies, I took complete ownership of the controller to handle the requests. For me, the major issue that drove me away from OmniAuth was the difficulty in debugging issues. With all of the HTTP requests happening in deeply abstracted Rack middlewares (needing to look in the `omniauth` gem, the `omniauth-oauth2` gem, and then the provider strategy gem itself). So, I simply took ownership. Here is real production code for what that looked like in a project:

https://gist.github.com/fractaledmind/762a76ba245196b4d506c666bea1e0f2

As I said, I'm just sharing in case this proves helpful to you. Big fan of the vision you have for `rubymonolith` BTW.

**Comment by bradgessler** [comment]
Thanks for sharing! I'm going to continue down the "OAuth from Scratch" approach because I'm finding that it's really simple and integrating with Rails security features is much easier.
